services:
  - type: web
    name: template-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true

databases:
  - name: template-db
    databaseName: templatedb
    plan: free
